set(DEP_KIND source)
# allow using system
set(DEP_SOURCE_SYSTEM ON)

function(pugixml_post_resolve mode local_path os arch version)
    if(TARGET pugixml)
        return()
    endif()
    if(mode STREQUAL "system")
        find_package(PkgConfig REQUIRED)
        pkg_check_modules(pugixml REQUIRED IMPORTED_TARGET pugixml)
        add_library(pugixml INTERFACE IMPORTED GLOBAL)
        target_link_libraries(pugixml INTERFACE PkgConfig::pugixml)
    else()
        set(_src "${local_path}/pugixml/src")
        add_library(pugixml STATIC "${_src}/pugixml.cpp")
        target_include_directories(pugixml PUBLIC "${_src}")
        set_target_properties(pugixml PROPERTIES POSITION_INDEPENDENT_CODE ON UNITY_BUILD OFF)
    endif()
endfunction()
