cmake_minimum_required(VERSION 3.25)

get_filename_component(_EXTDEPS_ROOT "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
include("${CMAKE_CURRENT_LIST_DIR}/build_dependency.cmake")

function(_extdeps_windows_link_name prefix libname config out)
    set(_names "${libname}")
    string(TOUPPER "${config}" _config)
    if(_config STREQUAL "DEBUG")
        list(PREPEND _names "${libname}d")
    endif()

    foreach(_name ${_names})
        if(EXISTS "${prefix}/lib/${_name}.lib")
            set(${out} "${_name}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    # Let the existing missing-library diagnostic report the exact expected path.
    list(GET _names 0 _name)
    set(${out} "${_name}" PARENT_SCOPE)
endfunction()

# Resolve shared libraries from an installed prefix
function(_extdeps_resolve_libs prefix os config libnames out_link out_bundle)
    set(_link_libs "")
    set(_bundle_libs "")

    foreach(_lib_name ${libnames})
        if(os STREQUAL "windows")
            _extdeps_windows_link_name("${prefix}" "${_lib_name}" "${config}" _windows_lib_name)
            list(APPEND _link_libs "${prefix}/lib/${_windows_lib_name}.lib")
            file(GLOB _runtime_libs "${prefix}/bin/${_windows_lib_name}.dll" "${prefix}/bin/${_windows_lib_name}[0-9]*.dll")
            list(APPEND _bundle_libs ${_runtime_libs})
        elseif(os STREQUAL "macos")
            file(GLOB _runtime_libs "${prefix}/lib/lib${_lib_name}.dylib" "${prefix}/lib/lib${_lib_name}.*dylib")
            list(APPEND _link_libs "${prefix}/lib/lib${_lib_name}.dylib")
            list(APPEND _bundle_libs ${_runtime_libs})
        else()
            file(GLOB _runtime_libs "${prefix}/lib/lib${_lib_name}.so" "${prefix}/lib/lib${_lib_name}.so.*")
            list(APPEND _link_libs "${prefix}/lib/lib${_lib_name}.so")
            list(APPEND _bundle_libs ${_runtime_libs})
        endif()
    endforeach()
    if(_link_libs)
        list(REMOVE_DUPLICATES _link_libs)
    endif()
    if(_bundle_libs)
        list(REMOVE_DUPLICATES _bundle_libs)
    endif()
    set(${out_link} "${_link_libs}" PARENT_SCOPE)
    set(${out_bundle} "${_bundle_libs}" PARENT_SCOPE)
endfunction()

# Create one imported interface target
function(_extdeps_make_target target include_dirs link_libraries)
    if(target AND NOT TARGET ${target})
        add_library(${target} INTERFACE IMPORTED GLOBAL)
        # non-SYSTEM so dep headers have the priority over system headers
        set_property(TARGET ${target} PROPERTY SYSTEM FALSE)
        target_include_directories(${target} INTERFACE ${include_dirs})
        target_link_libraries(${target} INTERFACE ${link_libraries})
    endif()
endfunction()

# Include dirs for an installed prefix
function(_extdeps_incdirs prefix out)
    set(_include_dirs "${prefix}/include")
    foreach(_subdir ${DEP_INCLUDE_SUBDIRS})
        list(APPEND _include_dirs "${prefix}/include/${_subdir}")
    endforeach()
    set(${out} "${_include_dirs}" PARENT_SCOPE)
endfunction()

# Get library names for a given OS
macro(_extdeps_libnames os out)
    # Windows base lib names can be overriden by DEP_LIBS_WINDOWS
    if(${os} STREQUAL "windows" AND DEFINED DEP_LIBS_WINDOWS)
        set(${out} "${DEP_LIBS_WINDOWS}")
    else()
        set(${out} "${DEP_LIBS}")
    endif()
endmacro()

# Resolve link and bundle libraries from an installed prefix
function(_extdeps_resolve_prefix_libs prefix os config libnames out_link out_bundle)
    if(DEP_STATIC)
        set(_link_libs "")
        set(_bundle_libs "")
        foreach(_lib_name ${libnames})
            if(os STREQUAL "windows")
                _extdeps_windows_link_name("${prefix}" "${_lib_name}" "${config}" _windows_lib_name)
                list(APPEND _link_libs "${prefix}/lib/${_windows_lib_name}.lib")
            else()
                list(APPEND _link_libs "${prefix}/lib/lib${_lib_name}.a")
            endif()
        endforeach()
    else()
        _extdeps_resolve_libs("${prefix}" "${os}" "${config}" "${libnames}" _link_libs _bundle_libs)
        if(os STREQUAL "windows" AND DEP_STATIC_WINDOWS)
            set(_bundle_libs "")
        endif()
    endif()
    set(${out_link} "${_link_libs}" PARENT_SCOPE)
    set(${out_bundle} "${_bundle_libs}" PARENT_SCOPE)
endfunction()

# Normalize imported target metadata to "target|libs" entries
macro(_extdeps_target_entries fallback_libs out)
    if(DEFINED DEP_TARGETS)
        set(${out} "${DEP_TARGETS}")
    else()
        string(REPLACE ";" " " _fallback_libs_string "${fallback_libs}")
        set(${out} "${DEP_TARGET}|${_fallback_libs_string}")
    endif()
endmacro()

# Split one "target|lib1 lib2" entry into its target name + lib list.
macro(_extdeps_parse_entry entry out_target out_libs)
    string(REPLACE "|" ";" _entry_fields "${entry}")
    list(GET _entry_fields 0 ${out_target})
    list(GET _entry_fields 1 _libs_string)
    string(REPLACE " " ";" ${out_libs} "${_libs_string}")
endmacro()

# Resolve libraries for an installed prefix
function(_extdeps_resolve_installed name prefix os config)
    _extdeps_incdirs("${prefix}" _include_dirs)
    _extdeps_libnames("${os}" _lib_names)
    _extdeps_target_entries("${_lib_names}" _entries)
    set(_primary_link "")
    set(_all_bundle "")
    set(_first TRUE)
    foreach(_entry ${_entries})
        _extdeps_parse_entry("${_entry}" _target _libs)
        _extdeps_resolve_prefix_libs("${prefix}" "${os}" "${config}" "${_libs}" _link _bundle)
        foreach(_link_lib ${_link})
            if(NOT EXISTS "${_link_lib}")
                message(FATAL_ERROR "[${name}] resolved lib missing: ${_link_lib}")
            endif()
        endforeach()
        if(_first AND DEP_LINK_DEPS)
            list(APPEND _link ${DEP_LINK_DEPS})
        endif()
        _extdeps_make_target("${_target}" "${_include_dirs}" "${_link}")
        list(APPEND _all_bundle ${_bundle})
        if(_first)
            set(_primary_link "${_link}")
            set(_first FALSE)
        endif()
    endforeach()
    set_property(GLOBAL PROPERTY ${name}_INCLUDE_DIRS ${_include_dirs})
    set_property(GLOBAL PROPERTY ${name}_LIBRARIES ${_primary_link})
    set_property(GLOBAL PROPERTY ${name}_INSTALL_LIBRARIES ${_all_bundle})
    message(STATUS "[${name}] bundle: ${_all_bundle}")
endfunction()

# Find system libraries by base name
function(_extdeps_find_system_libs name libnames out)
    set(_libs "")
    foreach(_lib_name ${libnames})
        find_library(${name}_LIB_${_lib_name} NAMES ${_lib_name})
        if(NOT ${name}_LIB_${_lib_name})
            message(FATAL_ERROR "[${name}] system lib '${_lib_name}' not found (USE_SYSTEM)")
        endif()
        list(APPEND _libs "${${name}_LIB_${_lib_name}}")
    endforeach()
    set(${out} "${_libs}" PARENT_SCOPE)
endfunction()

# SYSTEM mode: find headers + libs on the system
function(_extdeps_resolve_system name)
    find_path(${name}_INC NAMES ${DEP_SYSTEM_HEADER})
    if(NOT ${name}_INC)
        message(FATAL_ERROR "[${name}] system header '${DEP_SYSTEM_HEADER}' not found (USE_SYSTEM)")
    endif()
    set(_include_dirs "${${name}_INC}")
    foreach(_subdir ${DEP_INCLUDE_SUBDIRS})
        list(APPEND _include_dirs "${${name}_INC}/${_subdir}")
    endforeach()
    _extdeps_target_entries("${DEP_LIBS}" _entries)
    set(_primary_libs "")
    set(_first TRUE)
    foreach(_entry ${_entries})
        _extdeps_parse_entry("${_entry}" _target _libs)
        _extdeps_find_system_libs("${name}" "${_libs}" _found)
        _extdeps_make_target("${_target}" "${_include_dirs}" "${_found}")
        if(_first)
            set(_primary_libs "${_found}")
            set(_first FALSE)
        endif()
    endforeach()
    set_property(GLOBAL PROPERTY ${name}_INCLUDE_DIRS ${_include_dirs})
    set_property(GLOBAL PROPERTY ${name}_LIBRARIES ${_primary_libs})
    set_property(GLOBAL PROPERTY ${name}_INSTALL_LIBRARIES "")
endfunction()

# Build from source
function(_extdeps_build name local_path os arch config)
    set(_dep_prefixes "")
    foreach(_dep_name ${DEP_DEPENDS})
        list(APPEND _dep_prefixes "${local_path}/../${_dep_name}")
    endforeach()
    build_dep(NAME ${name} RECIPE_DIR "${_EXTDEPS_ROOT}/recipes/${name}"
              OS ${os} ARCH ${arch} CONFIG "${config}"
              WORK "${local_path}/work" INSTALL_DIR "${local_path}"
              DEPENDS_PREFIXES "${_dep_prefixes}")
endfunction()

# Fetch a locked prebuilt archive
function(_extdeps_fetch_prebuilt name local_path os arch version out)
    set(${out} FALSE PARENT_SCOPE)
    set(_lock_file "${_EXTDEPS_ROOT}/prebuilt.lock")
    if(NOT os OR NOT arch OR NOT EXISTS "${_lock_file}")
        return()
    endif()

    file(STRINGS "${_lock_file}" _lock_entry REGEX "^${name} ${version} ${os} ${arch} ")
    list(LENGTH _lock_entry _entry_count)

    # Fallback to universal macOS prebuilt if no arch-specific entry exists
    if(NOT _entry_count EQUAL 1 AND os STREQUAL "macos")
        file(STRINGS "${_lock_file}" _lock_entry REGEX "^${name} ${version} ${os} universal ")
        list(LENGTH _lock_entry _entry_count)
    endif()
    # No prebuilt found, will fallback to building from source
    if(NOT _entry_count EQUAL 1)
        return()
    endif()

    string(REPLACE " " ";" _lock_fields "${_lock_entry}")
    list(LENGTH _lock_fields _field_count)
    if(NOT _field_count EQUAL 7)
        message(STATUS "[${name}] malformed lock entry, building from source")
        return()
    endif()
    list(GET _lock_fields 2 _lock_os)
    list(GET _lock_fields 3 _lock_arch)
    list(GET _lock_fields 4 _archive_name)
    list(GET _lock_fields 5 _sha256)
    list(GET _lock_fields 6 _release)

    # Check the recipe signature
    _bd_recipe_sig("${_EXTDEPS_ROOT}/recipes/${name}" "${_lock_os}" "${_lock_arch}" _current_sig)
    string(SUBSTRING "${_current_sig}" 0 12 _current_sig)
    if(NOT _archive_name MATCHES "-${_current_sig}\\.7z$")
        message(STATUS "[${name}] lock entry ${_archive_name} doesn't match the local recipe (${_current_sig}), building from source")
        return()
    endif()

    # Check if the prebuilt is already installed
    set(_stamp "${local_path}/.prebuilt")
    if(EXISTS "${_stamp}")
        file(READ "${_stamp}" _previous_archive)
        if(_previous_archive STREQUAL "${_archive_name}")
            set(${out} TRUE PARENT_SCOPE)
            return()
        endif()
    endif()

    # Check if the prebuilt is already cached
    _bd_resolve_cache(_cache)
    set(_archive "${_cache}/prebuilt/${_archive_name}")
    set(_ok FALSE)
    if(EXISTS "${_archive}")
        file(SHA256 "${_archive}" _got_sha256)
        if(_got_sha256 STREQUAL "${_sha256}")
            set(_ok TRUE)
        endif()
    endif()

    # Download the prebuilt archive if not cached or checksum mismatch
    if(NOT _ok)
        file(MAKE_DIRECTORY "${_cache}/prebuilt")
        _bd_try_fetch("${_archive}" "${_sha256}" _ok
                      "${EXTDEPS_PREBUILT_URL}/${_release}/${_archive_name}")
    endif()

    # Oh well, rebuild then
    if(NOT _ok)
        return()
    endif()

    file(REMOVE_RECURSE "${local_path}")
    file(MAKE_DIRECTORY "${local_path}")
    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${local_path}")
    file(WRITE "${_stamp}" "${_archive_name}")
    set(${out} TRUE PARENT_SCOPE)
endfunction()

# Split a DEP_PATCHES entry into apply dir + patch path
macro(_extdeps_patch_entry entry sole out_dir out_rel)
    string(FIND "${entry}" "|" _separator)

    # this is a workaround for multi-source deps, patch can be prefixed with a source subdir
    # it is not used currently, leftover from lv2 migration, but may be useful in the future
    if(_separator GREATER -1)
        string(REPLACE "|" ";" _patch_fields "${entry}")
        list(GET _patch_fields 0 ${out_dir})
        list(GET _patch_fields 1 ${out_rel})
    elseif("${sole}" STREQUAL "")
        message(FATAL_ERROR "[${name}] DEP_PATCHES '${entry}' needs a '<dir>|' prefix (dep has multiple source trees)")
    else()
        set(${out_dir} "${sole}")
        set(${out_rel} "${entry}")
    endif()
endmacro()

# Fetch and populate source deps
function(_extdeps_populate_source name local_path)

    foreach(_source ${DEP_SOURCES})
        # each entry is "<subdir>|<kind>|<location>|<pin>"
        # - subdir: the subdirectory to populate under the dep's local_path
        # - kind: "tarball" or "local" or "git"
        # - location: the URL or local path to fetch from
        # - pin: the expected SHA256 for tarballs, or git commit hash for git
        _bd_parse_source("${_source}" _source_subdir _source_kind _source_location _source_pin)

        # local is a special case, we use it as is
        if(_source_kind STREQUAL "local")
            get_filename_component(_source_basename "${_source_location}" NAME)
            if(NOT IS_DIRECTORY "${_source_location}")
                message(FATAL_ERROR "[${name}] local source not found: ${_source_location}")
            elseif(NOT _source_basename STREQUAL _source_subdir)
                message(FATAL_ERROR "[${name}] local source dir must be named '${_source_subdir}': ${_source_location}")
            endif()
            get_filename_component(_source_parent "${_source_location}" DIRECTORY)
            message(STATUS "[${name}] local source: ${_source_location}")
            set_property(GLOBAL PROPERTY ${name}_SOURCE_DIR "${_source_parent}")
            return()
        endif()
    endforeach()

    # Check if this is single source or multi-source dep
    set(_subs "")
    foreach(_source ${DEP_SOURCES})
        _bd_parse_source("${_source}" _source_subdir _source_kind _source_location _source_pin)
        list(APPEND _subs "${_source_subdir}")
    endforeach()
    list(REMOVE_DUPLICATES _subs)
    list(LENGTH _subs _sub_count)
    set(_sole "")
    if(_sub_count EQUAL 1)
        set(_sole "${_subs}")
    endif()

    _bd_resolve_cache(_cache)
    set(_download_dir "${_cache}/downloads/${name}")
    file(MAKE_DIRECTORY "${_download_dir}")
    set(_recipe_dir "${_EXTDEPS_ROOT}/recipes/${name}")

    # Collect patches for the signature
    set(_pins "${DEP_SOURCES}")
    foreach(_patch_entry ${DEP_PATCHES})
        _extdeps_patch_entry("${_patch_entry}" "${_sole}" _patch_dir _patch_rel)
        file(SHA256 "${_recipe_dir}/${_patch_rel}" _patch_sha256)
        list(APPEND _pins "${_patch_entry}@${_patch_sha256}")
    endforeach()

    # Calculate a signature for the current source + patches
    string(SHA256 _wanted_stamp "${_pins}")
    set(_existing_stamp "")
    if(EXISTS "${local_path}/.populated")
        file(READ "${local_path}/.populated" _existing_stamp)
        string(STRIP "${_existing_stamp}" _existing_stamp)
    endif()

    # If the signature doesn't match, re-populate the source dir
    if(NOT _existing_stamp STREQUAL _wanted_stamp)
        file(REMOVE_RECURSE "${local_path}")
        file(MAKE_DIRECTORY "${local_path}")
        find_program(GIT NAMES git REQUIRED)
        foreach(_source ${DEP_SOURCES})
            _bd_parse_source("${_source}" _source_subdir _source_kind _source_location _source_pin)
            if(_source_kind STREQUAL "tarball")
                get_filename_component(_basename "${_source_location}" NAME)
                if(NOT EXISTS "${_download_dir}/${_basename}")
                    _bd_mirror("${_EXTDEPS_ROOT}" _mirror)
                    set(_urls "")
                    if(_mirror)
                        _bd_src_ext("${_basename}" _ext)
                        if(_source_subdir STREQUAL name)
                            list(APPEND _urls "${_mirror}/${name}-${version}-src.${_ext}")
                        else()
                            list(APPEND _urls "${_mirror}/${name}-${_source_subdir}-src.${_ext}")
                        endif()
                    endif()
                    list(APPEND _urls "${_source_location}")
                    _bd_fetch("${_download_dir}/${_basename}" "${_source_pin}" ${_urls})
                endif()
                if(NOT EXISTS "${local_path}/${_source_subdir}")
                    set(_extract_dir "${local_path}/.ex_${_source_subdir}")
                    file(MAKE_DIRECTORY "${_extract_dir}")
                    file(ARCHIVE_EXTRACT INPUT "${_download_dir}/${_basename}" DESTINATION "${_extract_dir}")
                    file(GLOB _top LIST_DIRECTORIES true "${_extract_dir}/*")
                    list(GET _top 0 _source_root)
                    file(RENAME "${_source_root}" "${local_path}/${_source_subdir}")
                    file(REMOVE_RECURSE "${_extract_dir}")
                endif()
            else()
                set(_git_dir "${_download_dir}/${_source_subdir}.git")
                if(NOT EXISTS "${_git_dir}/.git")
                    _bd_run(${GIT} clone --quiet "${_source_location}" "${_git_dir}")
                endif()
                _bd_run_dir("${_git_dir}" ${GIT} checkout --quiet "${_source_pin}")
                execute_process(COMMAND ${GIT} -C "${_git_dir}" rev-parse HEAD
                                OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE)
                if(NOT _head STREQUAL "${_source_pin}")
                    message(FATAL_ERROR "[${name}] ${_source_subdir}: HEAD ${_head} != pinned ${_source_pin}")
                endif()
                if(NOT EXISTS "${local_path}/${_source_subdir}")
                    file(COPY "${_git_dir}/" DESTINATION "${local_path}/${_source_subdir}" PATTERN ".git" EXCLUDE)
                endif()
            endif()
        endforeach()

        # Apply patches
        foreach(_patch_entry ${DEP_PATCHES})
            _extdeps_patch_entry("${_patch_entry}" "${_sole}" _patch_subdir _patch_rel)
            message(STATUS "[${name}] patch ${_patch_rel}")
            _bd_run(${CMAKE_COMMAND} -E env "GIT_DIR=${local_path}/.no-such-repo"
                    ${GIT} apply --whitespace=nowarn "${_recipe_dir}/${_patch_rel}"
                    WORKING_DIRECTORY "${local_path}/${_patch_subdir}")
        endforeach()
        file(WRITE "${local_path}/.populated" "${_wanted_stamp}\n")
    endif()
    set_property(GLOBAL PROPERTY ${name}_SOURCE_DIR "${local_path}")
endfunction()

# Fetch a binary tool
function(_extdeps_fetch_binary_tool name local_path os arch)
    if(NOT DEFINED DEP_BINARY_FILE_${os}-${arch})
        message(FATAL_ERROR "[${name}] no binary for ${os}/${arch}")
    endif()
    set(_file "${DEP_BINARY_FILE_${os}-${arch}}")
    set(_sha256 "${DEP_BINARY_SHA256_${os}-${arch}}")
    set(_binary_name "${DEP_BINARY_NAME}")
    if(os STREQUAL "windows")
        string(APPEND _binary_name ".exe")
    endif()
    set(_dest "${local_path}/bin/${_binary_name}")
    if(EXISTS "${_dest}")
        file(SHA256 "${_dest}" _got_sha256)
        if(_got_sha256 STREQUAL "${_sha256}")
            return()
        endif()
    endif()
    file(MAKE_DIRECTORY "${local_path}/bin")
    _bd_try_fetch("${_dest}" "${_sha256}" _ok "${DEP_BINARY_URL_ROOT}/${_file}")
    if(NOT _ok)
        message(FATAL_ERROR "[${name}] binary tool fetch failed: ${DEP_BINARY_URL_ROOT}/${_file}")
    endif()
    file(CHMOD "${_dest}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
         GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endfunction()

# Use the prebuilt for this mode/config, else build from source
function(_extdeps_use_prebuilt mode config out)
    if(NOT mode STREQUAL "rebuild" AND config STREQUAL "RelWithDebInfo")
        set(${out} TRUE PARENT_SCOPE)
    else()
        set(${out} FALSE PARENT_SCOPE)
    endif()
endfunction()

# Resolve one dependency
function(extdeps_resolve name version mode local_path os arch config)
    if(COMMAND ${name}_resolve_override)
        cmake_language(CALL ${name}_resolve_override "${mode}" "${local_path}" "${os}" "${arch}" "${version}" "${config}")
        return()
    endif()

    if(NOT DEFINED DEP_KIND OR DEP_KIND STREQUAL "library")
        if(mode STREQUAL "system")
            _extdeps_resolve_system("${name}")
        else()
            _extdeps_use_prebuilt("${mode}" "${config}" _use_prebuilt)
            set(_ok FALSE)
            if(_use_prebuilt)
                _extdeps_fetch_prebuilt("${name}" "${local_path}" "${os}" "${arch}" "${version}" _ok)
            endif()
            if(NOT _ok)
                _extdeps_build("${name}" "${local_path}" "${os}" "${arch}" "${config}")
            endif()
            _extdeps_resolve_installed("${name}" "${local_path}" "${os}" "${config}")
        endif()

    elseif(DEP_KIND STREQUAL "source")
        # SYSTEM mode doesn't have any sources
        if(NOT mode STREQUAL "system")
            _extdeps_populate_source("${name}" "${local_path}")
        endif()

    elseif(DEP_KIND STREQUAL "tool")
        if(mode STREQUAL "system")
            find_program(${name}_EXE NAMES ${name})
            if(NOT ${name}_EXE)
                message(FATAL_ERROR "[${name}] system tool not found (USE_SYSTEM)")
            endif()
            get_filename_component(_bin_dir "${${name}_EXE}" DIRECTORY)
            set_property(GLOBAL PROPERTY ${name}_BIN_DIR "${_bin_dir}")
        elseif(DEFINED DEP_BINARY_URL_ROOT)
            _extdeps_fetch_binary_tool("${name}" "${local_path}" "${os}" "${arch}")
            set_property(GLOBAL PROPERTY ${name}_BIN_DIR "${local_path}/bin")
        else()
            if(mode STREQUAL "rebuild")
                _extdeps_build("${name}" "${local_path}" "${os}" "${arch}" "RelWithDebInfo")
            else()
                _extdeps_fetch_prebuilt("${name}" "${local_path}" "${os}" "${arch}" "${version}" _ok)
                if(NOT _ok)
                    message(WARNING "[${name}] no usable prebuilt for ${os}/${arch}, building from source")
                    _extdeps_build("${name}" "${local_path}" "${os}" "${arch}" "RelWithDebInfo")
                endif()
            endif()
            set_property(GLOBAL PROPERTY ${name}_BIN_DIR "${local_path}/bin")
        endif()

    else()
        message(FATAL_ERROR "[${name}] unknown DEP_KIND: ${DEP_KIND}")
    endif()

    if(COMMAND ${name}_post_resolve)
        cmake_language(CALL ${name}_post_resolve "${mode}" "${local_path}" "${os}" "${arch}" "${version}")
    endif()
endfunction()
