set(DEP_VERSION 1.12)

set(DEP_SOURCE_URL    "https://github.com/Chlumsky/msdfgen/archive/refs/tags/v1.12.tar.gz")
set(DEP_SOURCE_SHA256 "f058117496097217d12e4ea86adbff8467adaf6f12af793925d243b86b0c4f57")

set(DEP_DEPENDS freetype)

set(DEP_CMAKE_ARGS
    -DBUILD_SHARED_LIBS=ON
    -DMSDFGEN_CORE_ONLY=OFF
    -DMSDFGEN_BUILD_STANDALONE=OFF
    -DMSDFGEN_USE_VCPKG=OFF
    -DMSDFGEN_USE_OPENMP=OFF
    -DMSDFGEN_USE_SKIA=OFF
    -DMSDFGEN_INSTALL=ON
    -DMSDFGEN_DISABLE_SVG=ON
    -DMSDFGEN_DISABLE_PNG=ON
)

set(DEP_LICENSE_FILES LICENSE.txt)
