set(DEP_KIND source)
set(DEP_SOURCE_SYSTEM ON)   # allow using system version

function(utfcpp_post_resolve mode local_path os arch version)
    if(TARGET utfcpp)
        return()
    endif()
    add_library(utfcpp INTERFACE IMPORTED GLOBAL)
    if(mode STREQUAL "system")
        find_package(utf8cpp CONFIG QUIET)
        if(TARGET utf8::cpp)
            target_link_libraries(utfcpp INTERFACE utf8::cpp)
        else()
            find_path(UTFCPP_INCLUDE_DIR NAMES utf8.h PATH_SUFFIXES utf8cpp)
            if(NOT UTFCPP_INCLUDE_DIR)
                message(FATAL_ERROR "[utfcpp] utf8cpp not found")
            endif()
            target_include_directories(utfcpp INTERFACE "${UTFCPP_INCLUDE_DIR}")
        endif()
    else()
        target_include_directories(utfcpp INTERFACE "${local_path}/utfcpp/source")
    endif()
endfunction()
