set(DEP_KIND source)
set(DEP_SOURCE_SYSTEM ON)   # allow using system version

function(utfcpp_post_resolve mode local_path os arch version)
    if(TARGET utfcpp)
        return()
    endif()
    add_library(utfcpp INTERFACE IMPORTED GLOBAL)
    if(mode STREQUAL "system")
        find_package(utf8cpp REQUIRED CONFIG)
        target_link_libraries(utfcpp INTERFACE utf8::cpp)
    else()
        target_include_directories(utfcpp INTERFACE "${local_path}/utfcpp/source")
    endif()
endfunction()
