function(_wxwidgets_resolve_local_lib prefix os libname out_link out_bundle)
    if(os STREQUAL "macos")
        set(_link "${prefix}/lib/lib${libname}.dylib")
        file(GLOB _bundle "${prefix}/lib/lib${libname}.dylib" "${prefix}/lib/lib${libname}.*dylib")
    else()
        set(_link "${prefix}/lib/lib${libname}.so")
        file(GLOB _bundle "${prefix}/lib/lib${libname}.so" "${prefix}/lib/lib${libname}.so.*")
    endif()
    if(NOT EXISTS "${_link}")
        message(FATAL_ERROR "[wxwidgets] wx-config requested ${libname}, but ${_link} is missing")
    endif()
    if(_bundle)
        list(REMOVE_DUPLICATES _bundle)
    endif()
    set(${out_link} "${_link}" PARENT_SCOPE)
    set(${out_bundle} "${_bundle}" PARENT_SCOPE)
endfunction()

function(_wxwidgets_set_from_wxconfig wxconfig prefix os)
    set(_pfx "")
    if (NOT "${prefix}" STREQUAL "")
        set(_pfx --prefix=${prefix} --exec-prefix=${prefix})
    endif()
    execute_process(COMMAND ${wxconfig} ${_pfx} --cxxflags base
                    OUTPUT_VARIABLE wx_cxx ERROR_VARIABLE wx_err
                    RESULT_VARIABLE wx_rc OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT wx_rc EQUAL 0)
        message(FATAL_ERROR "[wxwidgets] ${wxconfig} --cxxflags base failed: ${wx_err}")
    endif()
    execute_process(COMMAND ${wxconfig} ${_pfx} --libs base
                    OUTPUT_VARIABLE wx_libs ERROR_VARIABLE wx_err
                    RESULT_VARIABLE wx_rc OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT wx_rc EQUAL 0)
        message(FATAL_ERROR "[wxwidgets] ${wxconfig} --libs base failed: ${wx_err}")
    endif()
    separate_arguments(wx_cxx_list NATIVE_COMMAND "${wx_cxx}")
    separate_arguments(wx_libs_list NATIVE_COMMAND "${wx_libs}")

    set(incs "")
    set(opts "")
    foreach(f ${wx_cxx_list})
        if (f MATCHES "^-I(.+)")
            list(APPEND incs ${CMAKE_MATCH_1})
        else()
            list(APPEND opts ${f})
        endif()
    endforeach()

    set(install_libs "")
    if (NOT "${prefix}" STREQUAL "")
        set(link_libs "")
        foreach(f ${wx_libs_list})
            if(f MATCHES "^-l(wx.+)")
                _wxwidgets_resolve_local_lib("${prefix}" "${os}" "${CMAKE_MATCH_1}" _link _bundle)
                list(APPEND link_libs "${_link}")
                list(APPEND install_libs ${_bundle})
            elseif(NOT f MATCHES "^-L")
                list(APPEND link_libs ${f})
            endif()
        endforeach()
        if(install_libs)
            list(REMOVE_DUPLICATES install_libs)
        endif()
    else()
        set(link_libs ${wx_libs_list})
    endif()

    if(NOT TARGET wxwidgets::wxwidgets)
       add_library(wxwidgets::wxwidgets INTERFACE IMPORTED GLOBAL)
       target_include_directories(wxwidgets::wxwidgets INTERFACE ${incs})
       target_compile_options(wxwidgets::wxwidgets INTERFACE ${opts})
       target_link_libraries(wxwidgets::wxwidgets INTERFACE ${link_libs})
    endif()
    set_property(GLOBAL PROPERTY wxwidgets_INCLUDE_DIRS ${incs})
    set_property(GLOBAL PROPERTY wxwidgets_LIBRARIES ${link_libs})
    set_property(GLOBAL PROPERTY wxwidgets_INSTALL_LIBRARIES ${install_libs})
endfunction()

# Windows has no wx-config
function(_wxwidgets_set_windows prefix)
    file(GLOB _libdir "${prefix}/lib/vc_*dll")
    list(LENGTH _libdir _n)
    if(NOT _n EQUAL 1)
        message(FATAL_ERROR "[wxwidgets] expected one lib/vc_*dll dir in ${prefix}, found: ${_libdir}")
    endif()
    file(GLOB _setup_hdr "${_libdir}/baseu/wx/setup.h" "${_libdir}/baseud/wx/setup.h")
    list(LENGTH _setup_hdr _nsetup)
    if(NOT _nsetup EQUAL 1)
        message(FATAL_ERROR "[wxwidgets] expected one base setup dir under ${_libdir}, found: ${_setup_hdr}")
    endif()
    get_filename_component(_setup_dir "${_setup_hdr}" DIRECTORY)
    get_filename_component(_setup_dir "${_setup_dir}" DIRECTORY)
    set(incs ${prefix}/include ${_setup_dir})
    file(GLOB libs "${_libdir}/wxbase*.lib")
    list(FILTER libs EXCLUDE REGEX "(_net|_xml)\\.lib$")
    file(GLOB install "${_libdir}/wxbase*.dll")
    list(FILTER install EXCLUDE REGEX "(_net|_xml)\\.dll$")
    if(NOT libs)
        message(FATAL_ERROR "[wxwidgets] no wxbase*.lib in ${_libdir}")
    endif()
    if(NOT install)
        message(FATAL_ERROR "[wxwidgets] no wxbase*.dll in ${_libdir}")
    endif()
    if(NOT TARGET wxwidgets::wxwidgets)
       add_library(wxwidgets::wxwidgets INTERFACE IMPORTED GLOBAL)
       target_include_directories(wxwidgets::wxwidgets INTERFACE ${incs})
       target_link_libraries(wxwidgets::wxwidgets INTERFACE ${libs})
    endif()
    set_property(GLOBAL PROPERTY wxwidgets_INCLUDE_DIRS ${incs})
    set_property(GLOBAL PROPERTY wxwidgets_LIBRARIES ${libs})
    set_property(GLOBAL PROPERTY wxwidgets_INSTALL_LIBRARIES ${install})
endfunction()

function(wxwidgets_resolve_override mode local_path os arch version config)
    if(mode STREQUAL "system")
        find_program(WX_CONFIG NAMES wx-config)
        if(NOT WX_CONFIG)
            message(FATAL_ERROR "[wxwidgets] wx-config not found (install system wxWidgets dev package)")
        endif()
        _wxwidgets_set_from_wxconfig("${WX_CONFIG}" "" "${os}")
    else()
        set(_ok FALSE)
        _extdeps_use_prebuilt("${mode}" "${config}" _use_prebuilt)
        if(_use_prebuilt)
            _extdeps_fetch_prebuilt(wxwidgets "${local_path}" "${os}" "${arch}" "${version}" _ok)
        endif()
        if(NOT _ok)
            _extdeps_build(wxwidgets "${version}" "${local_path}" "${os}" "${arch}" "${config}")
        endif()
        if(os STREQUAL "windows")
            _wxwidgets_set_windows("${local_path}")
        else()
            file(GLOB _wxconfig "${local_path}/lib/wx/config/*")
            list(LENGTH _wxconfig _nconfig)
            if(NOT _nconfig EQUAL 1)
                message(FATAL_ERROR "[wxwidgets] expected one wx-config script in ${local_path}/lib/wx/config, found: ${_wxconfig}")
            endif()
            list(GET _wxconfig 0 _wxconfig)
            _wxwidgets_set_from_wxconfig("${_wxconfig}" "${local_path}" "${os}")
        endif()
    endif()
endfunction()
