set(DEP_KIND source)
set(DEP_SOURCE_SYSTEM ON)

function(rapidjson_add_to_build)
    if(TARGET rapidjson)
        return()
    endif()
    add_library(rapidjson INTERFACE)
    add_library(rapidjson::rapidjson ALIAS rapidjson)
    get_property(_src GLOBAL PROPERTY rapidjson_SOURCE_DIR)
    if(_src)
        target_include_directories(rapidjson INTERFACE "${_src}/rapidjson/include")
    else()
        find_path(RAPIDJSON_INCLUDE_DIR NAMES rapidjson/rapidjson.h REQUIRED)
        target_include_directories(rapidjson INTERFACE "${RAPIDJSON_INCLUDE_DIR}")
    endif()
endfunction()
