find_program(NINJA NAMES ninja REQUIRED)

function(_crashpad_select_gn_sub out)
    if(BD_OS STREQUAL "linux")
        if(BD_ARCH STREQUAL "aarch64")
            set(_sub "gn-linux-arm64")
        else()
            set(_sub "gn-linux-amd64")
        endif()
    elseif(BD_OS STREQUAL "macos")
        cmake_host_system_information(RESULT _host_cpu QUERY OS_PLATFORM)
        if(_host_cpu MATCHES "arm64|aarch64")
            set(_sub "gn-mac-arm64")
        else()
            set(_sub "gn-mac-amd64")
        endif()
    elseif(BD_OS STREQUAL "windows")
        set(_sub "gn-windows-amd64")
    else()
        message(FATAL_ERROR "[${BD_NAME}] unsupported OS: ${BD_OS}")
    endif()
    set(${out} "${_sub}" PARENT_SCOPE)
endfunction()

function(_crashpad_archive_ext basename out)
    if(basename MATCHES "\\.(tar\\.gz|tar\\.xz|tar\\.bz2|tgz|zip)$")
        set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        get_filename_component(_e "${basename}" LAST_EXT)
        string(REGEX REPLACE "^\\." "" _e "${_e}")
        set(${out} "${_e}" PARENT_SCOPE)
    endif()
endfunction()

_crashpad_select_gn_sub(_wanted_gn_sub)

function(_crashpad_clang_sub out)
    if(BD_OS STREQUAL "linux")
        if(BD_ARCH STREQUAL "aarch64")
            set(_sub "clang-linux-arm64")
        else()
            set(_sub "clang-linux-amd64")
        endif()
    elseif(BD_OS STREQUAL "windows")
        set(_sub "clang-windows-amd64")
    else()
        set(_sub "")
    endif()
    set(${out} "${_sub}" PARENT_SCOPE)
endfunction()
_crashpad_clang_sub(_wanted_clang_sub)

function(_crashpad_stage_source sub url sha dest)
    get_filename_component(_an "${url}" NAME)
    if(_an MATCHES "^git_revision:")
        set(_an "${BD_NAME}-${sub}.zip")
    else()
        _crashpad_archive_ext("${_an}" _cache_ext)
        set(_an "${BD_NAME}-${sub}.${_cache_ext}")
    endif()
    set(_dl "${BD_CACHE}/downloads/${BD_NAME}")
    set(_archive "${_dl}/${_an}")
    if(NOT EXISTS "${_archive}")
        file(MAKE_DIRECTORY "${_dl}")
        set(_urls "${url}")
        _bd_mirror("${_BD_REPO_ROOT}" _mirror)
        if(_mirror)
            _crashpad_archive_ext("${_an}" _ext)
            list(APPEND _urls "${_mirror}/${BD_NAME}-${sub}-src.${_ext}")
        endif()
        _bd_fetch("${_archive}" "${sha}" ${_urls})
    else()
        file(SHA256 "${_archive}" _got)
        if(NOT _got STREQUAL "${sha}")
            message(FATAL_ERROR "[${BD_NAME}] cached ${_an} SHA256 mismatch: ${_got} != ${sha}")
        endif()
    endif()

    set(_extract "${BUILD}/extract-${sub}")
    file(REMOVE_RECURSE "${_extract}" "${dest}")
    file(MAKE_DIRECTORY "${_extract}" "${dest}")
    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_extract}")
    file(GLOB _top LIST_DIRECTORIES true "${_extract}/*")
    list(LENGTH _top _n)
    if(_n EQUAL 1)
        list(GET _top 0 _root)
        if(IS_DIRECTORY "${_root}")
            file(COPY "${_root}/" DESTINATION "${dest}")
            return()
        endif()
    endif()
    file(COPY "${_extract}/" DESTINATION "${dest}")
endfunction()

function(_crashpad_stage_git sub repo commit dest)
    set(_gitdir "${BD_CACHE}/downloads/${BD_NAME}/${sub}.git")
    file(MAKE_DIRECTORY "${BD_CACHE}/downloads/${BD_NAME}")
    if(NOT EXISTS "${_gitdir}/.git")
        _bd_run(${GIT} clone --quiet "${repo}" "${_gitdir}")
    endif()
    _bd_run_dir("${_gitdir}" ${GIT} fetch --quiet origin "${commit}")
    _bd_run_dir("${_gitdir}" ${GIT} checkout --quiet "${commit}")
    execute_process(COMMAND ${GIT} -C "${_gitdir}" rev-parse HEAD
                    OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE
                    RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0 OR NOT _head STREQUAL "${commit}")
        message(FATAL_ERROR "[${BD_NAME}] ${sub}: HEAD ${_head} != pinned ${commit}")
    endif()
    file(REMOVE_RECURSE "${dest}")
    file(MAKE_DIRECTORY "${dest}")
    file(COPY "${_gitdir}/" DESTINATION "${dest}" PATTERN ".git" EXCLUDE)
endfunction()

foreach(_entry ${DEP_SOURCES})
    string(REPLACE "|" ";" _parts "${_entry}")
    list(GET _parts 0 _sub)
    list(GET _parts 1 _kind)
    list(GET _parts 2 _url)
    list(GET _parts 3 _sha)
    if(_sub STREQUAL "mini_chromium")
        _crashpad_stage_source("${_sub}" "${_url}" "${_sha}" "${SRC}/third_party/mini_chromium/mini_chromium")
    elseif(_sub STREQUAL "zlib")
        if(BD_OS STREQUAL "windows")
            _crashpad_stage_git("${_sub}" "${_url}" "${_sha}" "${SRC}/third_party/zlib/zlib")
        endif()
    elseif(_sub MATCHES "^gn-")
        if(NOT _kind STREQUAL "tarball")
            message(FATAL_ERROR "[${BD_NAME}] unsupported GN source kind for ${_sub}: ${_kind}")
        endif()
        if(_sub STREQUAL "${_wanted_gn_sub}")
            _crashpad_stage_source("${_sub}" "${_url}" "${_sha}" "${BUILD}/gn-tools/${_sub}")
        endif()
    elseif(_sub MATCHES "^clang-")
        if(_sub STREQUAL "${_wanted_clang_sub}")
            _crashpad_stage_source("${_sub}" "${_url}" "${_sha}" "${BUILD}/clang-tools/${_sub}")
        endif()
    else()
        message(FATAL_ERROR "[${BD_NAME}] unknown child source: ${_sub}")
    endif()
endforeach()

# linux-syscall-support - bundled with the recipe
file(MAKE_DIRECTORY "${SRC}/third_party/lss/lss")
file(COPY "${BD_RECIPE_DIR}/linux_syscall_support.h"
     DESTINATION "${SRC}/third_party/lss/lss")

if(BD_OS STREQUAL "windows")
    _bd_run(${CMAKE_COMMAND} -E env GIT_DIR=${BUILD}/.no-such-repo
            ${GIT} apply --whitespace=nowarn
            "${BD_RECIPE_DIR}/patch/0001-win_helper-vcvars-clean-env.patch"
            WORKING_DIRECTORY "${SRC}/third_party/mini_chromium/mini_chromium")
endif()

function(_crashpad_find_static_lib out name)
    set(_hints "")
    find_program(_cc NAMES cc gcc clang)
    if(_cc)
        execute_process(COMMAND "${_cc}" -print-multiarch
                        OUTPUT_VARIABLE _multiarch ERROR_QUIET
                        OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(_multiarch)
            list(APPEND _hints "/usr/lib/${_multiarch}")
        endif()
    endif()
    set(_old_suffixes "${CMAKE_FIND_LIBRARY_SUFFIXES}")
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
    set(_var "_crashpad_${name}_lib")
    unset(${_var} CACHE)
    if(_hints)
        find_library(${_var} NAMES "${name}" PATHS ${_hints} NO_DEFAULT_PATH)
    endif()
    if(NOT ${_var})
        unset(${_var} CACHE)
        find_library(${_var} NAMES "${name}" REQUIRED)
    endif()
    set(_lib "${${_var}}")
    unset(${_var} CACHE)
    set(CMAKE_FIND_LIBRARY_SUFFIXES "${_old_suffixes}")
    if(NOT _lib MATCHES "\\.a$")
        message(FATAL_ERROR "[${BD_NAME}] expected static ${name}, got: ${_lib}")
    endif()
    set(${out} "${_lib}" PARENT_SCOPE)
endfunction()


# Link to openssl statically, so we don't have to bundle them, and worry about their versions on linux
function(_crashpad_use_static_openssl)
    _crashpad_find_static_lib(_ssl "ssl")
    _crashpad_find_static_lib(_crypto "crypto")
    set(_file "${SRC}/util/BUILD.gn")
    file(READ "${_file}" _gn)
    set(_old "        libs = [
          \"crypto\",
          \"ssl\",
        ]")
    set(_new "        libs = [
          \"${_ssl}\",
          \"${_crypto}\",
        ]")
    string(REPLACE "${_old}" "${_new}" _patched "${_gn}")
    if(_patched STREQUAL _gn)
        message(FATAL_ERROR "[${BD_NAME}] failed to patch util/BUILD.gn for static OpenSSL")
    endif()
    file(WRITE "${_file}" "${_patched}")
endfunction()

if(BD_OS STREQUAL "linux")
    _crashpad_use_static_openssl()
endif()

function(_crashpad_select_gn out)
    if(BD_OS STREQUAL "windows")
        set(_exe "${BUILD}/gn-tools/${_wanted_gn_sub}/gn.exe")
    else()
        set(_exe "${BUILD}/gn-tools/${_wanted_gn_sub}/gn")
    endif()
    if(NOT EXISTS "${_exe}")
        message(FATAL_ERROR "[${BD_NAME}] GN not staged: ${_exe}")
    endif()
    if(NOT BD_OS STREQUAL "windows")
        file(CHMOD "${_exe}"
             PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
                         GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    endif()
    set(${out} "${_exe}" PARENT_SCOPE)
endfunction()

_crashpad_select_gn(GN)

function(_crashpad_build_one arch outdir)
    if(arch STREQUAL "aarch64")
        set(_cpu "arm64")
    elseif(arch STREQUAL "x86_64")
        set(_cpu "x64")
    else()
        message(FATAL_ERROR "[${BD_NAME}] unsupported arch: ${arch}")
    endif()

    set(_args "is_debug=false target_cpu=\"${_cpu}\"")
    if(BD_OS STREQUAL "linux")
        string(APPEND _args " use_sysroot=false")
        string(APPEND _args " crashpad_http_transport_impl=\"socket\"")
        string(APPEND _args " crashpad_use_boringssl_for_http_transport_socket=true")
    endif()

    _crashpad_clang_sub(_clang_sub)
    if(NOT _clang_sub STREQUAL "")
        set(_clang_dir "${BUILD}/clang-tools/${_clang_sub}")
        if(BD_OS STREQUAL "windows")
            set(_clang_probe "${_clang_dir}/bin/clang-cl.exe")
        else()
            set(_clang_probe "${_clang_dir}/bin/clang")
        endif()
        if(NOT EXISTS "${_clang_probe}")
            message(FATAL_ERROR "[${BD_NAME}] clang not staged: ${_clang_probe}")
        endif()
        string(APPEND _args " clang_path=\"${_clang_dir}\"")
    endif()

    _bd_run_dir("${SRC}" "${GN}" gen "${outdir}" "--args=${_args}")
    _bd_run_dir("${SRC}" "${NINJA}" -C "${outdir}" handler:crashpad_handler)
endfunction()

file(MAKE_DIRECTORY "${INSTALL}/bin")

if(BD_OS STREQUAL "macos" AND BD_ARCH STREQUAL "universal")
    _crashpad_build_one("x86_64" "${BUILD}/gn-x86_64")
    _crashpad_build_one("aarch64" "${BUILD}/gn-aarch64")
    find_program(LIPO NAMES lipo REQUIRED)
    _bd_run("${LIPO}" -create
            "${BUILD}/gn-x86_64/crashpad_handler"
            "${BUILD}/gn-aarch64/crashpad_handler"
            -output "${INSTALL}/bin/crashpad_handler")
else()
    _crashpad_build_one("${BD_ARCH}" "${BUILD}/gn")
    if(BD_OS STREQUAL "windows")
        file(COPY "${BUILD}/gn/crashpad_handler.exe" DESTINATION "${INSTALL}/bin")
    else()
        file(COPY "${BUILD}/gn/crashpad_handler" DESTINATION "${INSTALL}/bin")
    endif()
endif()

if(NOT BD_OS STREQUAL "windows")
    file(CHMOD "${INSTALL}/bin/crashpad_handler"
         PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
                     GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endif()

if(BD_OS STREQUAL "linux")
    execute_process(COMMAND ldd "${INSTALL}/bin/crashpad_handler"
                    OUTPUT_VARIABLE _ldd ERROR_VARIABLE _ldd_err
                    RESULT_VARIABLE _ldd_rc)
    if(NOT _ldd_rc EQUAL 0)
        message(FATAL_ERROR "[${BD_NAME}] ldd failed: ${_ldd_err}")
    endif()
    # check that we do not link dynamic OpenSSL
    if(_ldd MATCHES "lib(ssl|crypto)\\.so")
        message(FATAL_ERROR "[${BD_NAME}] crashpad_handler still links dynamic OpenSSL:\n${_ldd}")
    endif()
endif()
