# openssl, SYSTEM ONLY
function(openssl_resolve_override mode local_path os arch version)
    if(NOT mode STREQUAL "system")
        message(FATAL_ERROR "[openssl] only system mode is supported, use require_dep(openssl SYSTEM)")
    endif()
    find_package(OpenSSL REQUIRED)
    set_property(GLOBAL PROPERTY openssl_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
    set_property(GLOBAL PROPERTY openssl_LIBRARIES ${OPENSSL_LIBRARIES})
    set_property(GLOBAL PROPERTY openssl_INSTALL_LIBRARIES "")
endfunction()
