set(DEP_KIND source)
set(DEP_SOURCE_SYSTEM ON)

function(vst3sdk_post_resolve mode local_path os arch version)
    if(NOT mode STREQUAL "system")
        return()
    endif()
    foreach(_dir "${VST3SDK}" "$ENV{VST3SDK}" "/usr/src/vst3sdk" "/usr/share/vst3sdk")
        if(NOT "${_dir}" STREQUAL "" AND EXISTS "${_dir}/pluginterfaces/base/funknown.h")
            message(STATUS "[vst3sdk] VST3 SDK found at: ${_dir}")
            set_property(GLOBAL PROPERTY vst3sdk_SOURCE_DIR "${_dir}")
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "[vst3sdk] VST3 SDK not found (looked at \$VST3SDK, /usr/src/vst3sdk, /usr/share/vst3sdk)")
endfunction()
