get_property(_asiosdk_src GLOBAL PROPERTY asiosdk_SOURCE_DIR)
if(BD_OS STREQUAL "windows" AND _asiosdk_src)
    file(GLOB_RECURSE _asio_hdrs "${_asiosdk_src}/*.h")
    foreach(_h ${_asio_hdrs})
        if(_h MATCHES "/common/asio\\.h$")
            get_filename_component(_asio_common "${_h}" DIRECTORY)
            get_filename_component(_asiosdk_root "${_asio_common}" DIRECTORY)
            break()
        endif()
    endforeach()
    if(NOT _asiosdk_root)
        message(FATAL_ERROR "[${BD_NAME}] asiosdk source at ${_asiosdk_src} has no common/asio.h")
    endif()
    message(STATUS "[${BD_NAME}] ASIO enabled, SDK root: ${_asiosdk_root}")
    list(APPEND DEP_CMAKE_ARGS -DPA_USE_ASIO=ON "-DASIOSDK_ROOT_DIR=${_asiosdk_root}")
endif()

_bd_cmake_build("${SRC}")
